apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-master
  labels:
    app: {{ .Release.Name }}-redis
    role: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
      role: master
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
        role: master
    spec:
      containers:
      - name: {{ .Release.Name }}-redis-master
        image: redis:2.8.23
        ports:
        - name: redis-server
          containerPort: {{ .Values.redis.port }}
