apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-master
  labels:
    app: {{ .Release.Name }}-redis
    role: master
spec:
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: redis-server
  selector:
    app: {{ .Release.Name }}-redis
    role: master
