{{- if .Values.redis.slaveEnabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis-slave
  labels:
    app: {{ .Release.Name }}-redis
    role: slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Release.Name }}-redis
      role: slave
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-redis
        role: slave
    spec:
      containers:
      - name: {{ .Release.Name }}-redis-slave
        image: gcr.io/google_samples/gb-redisslave:v1
        ports:
        - name: redis-server
          containerPort: {{ .Values.redis.port }}
{{- end }}
