{{- if .Values.redis.slaveEnabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-slave
  labels:
    app: {{ .Release.Name }}-redis
    role: slave
spec:
  ports:
  - port: {{ .Values.redis.port }}
    targetPort: redis-server
  selector:
    app: {{ .Release.Name }}-redis
    role: slave
{{- end }}
