apiVersion: v1
entries:
  guestbook:
  - apiVersion: v1
    created: 2019-05-14T15:16:13.788085342+02:00
    description: A Helm chart to deploy Guestbook three tier web application.
    digest: a5e376cb443178f4ed762e606967c8e7eed830e3ee543987f8a34f9467f27872
    name: guestbook
    urls:
    - https://raw.githubusercontent.com/niklaushirt/guestbook/master/helm/repo/stable/guestbook-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v1
    created: 2019-05-14T15:16:13.787385294+02:00
    description: A Helm chart to deploy Guestbook three tier web application.
    digest: 6da0f3b7b8bc7502d28b31cb1743fadd804af4069840983353e9f5d59bd98f49
    name: guestbook
    urls:
    - https://raw.githubusercontent.com/niklaushirt/guestbook/master/helm/repo/stable/guestbook-0.1.0.tgz
    version: 0.1.0
generated: 2019-05-14T15:16:13.786671412+02:00
